spring:
  profiles:
    active: test
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**
server:
  servlet:
    session:
      cookie:
        name: CM_ID
logging:
  level:
    root: info
    sql: debug
    web: info
    cm: debug
  path: logFiles
  file:
    max-size: 10MB
  group:
    cm: com.mazhangjing.cloud.tuchuang
oss:
  accessKeyId: LTAIuSIeW67C---
  accessKeySecret: ZAcPfq1V7iE3----
  bucketName: cmb--d
  endpoint: oss-cn-shenzhen.---com
  fileHost: http://static2.mazhan------

baidu:
  appId: 16844---
  apiKey: XPjN10umuOl-----
  secureKey: Rbcs0bVYmDL2Ax-------

---
spring:
  profiles: test
  thymeleaf:
    cache: false

server:
  port: 8080
---
spring:
  profiles: real

server:
  port: 80
