spring:
  profiles:
    active: test
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**
server:
  servlet:
    session:
      cookie:
        name: CM_ID
logging:
  level:
    root: info
    sql: debug
    web: info
    cm: debug
  path: logFiles
  file:
    max-size: 10MB
  group:
    cm: com.mazhangjing.cloud.tuchuang
oss:
  accessKeyId: LTAIuSIeW67COQ6j
  accessKeySecret: ZAcPfq1V7iE3VZuy2CO9s8yj52nc0d
  bucketName: cmbed
  endpoint: oss-cn-shenzhen.aliyuncs.com
  fileHost: http://static2.mazhangjing.com

baidu:
  appId: 16844275
  apiKey: XPjN10umuOlZ8r2W1dgjwf14
  secureKey: Rbcs0bVYmDL2AxfFTx9tN4OoGxhFaCfi

---
spring:
  profiles: test
  thymeleaf:
    cache: false

server:
  port: 8080
---
spring:
  profiles: real

server:
  port: 80